/*
 * button.h
 *
 *  Created on: Aug 9, 2026
 *      Author: jacabe
 
 * Copyright (c) 2026 jacabe
 * Licensed under the MIT License.
 * See LICENSE file for details.

 */

#ifndef BUTTON_H_
#define BUTTON_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdint.h>
#include <stdbool.h>

#include "driver_gpio.h"
#include "gpio.h"




#ifndef WEAK
#define WEAK __attribute__((weak))
#endif

typedef enum{
	ACTIVE_LOW = 0,
	ACTIVE_HIGH
}button_active_state_t
;
typedef enum
{
	NO_REPEAT = 0,
	REPEAT
}button_repeat_t;

typedef enum
{
    BUTTON_OK = 0,
	BUTTON_NULL,
    BUTTON_ERROR,

    BUTTON_IDLE,
    BUTTON_PRESSED,
    BUTTON_HELD_SHORT,
    BUTTON_HELD_LONG,
    BUTTON_RELEASED_SHORT,
    BUTTON_RELEASED_LONG,
    BUTTON_REPEAT

} button_status_t;

typedef void (*button_callback_t)(void *obj);

typedef struct
{
    void (*short_pressed)(void *obj);
    void (*short_released)(void *obj);
    void (*long_pressed)(void *obj);
    void (*long_released)(void *obj);
    void (*repeated)(void *obj);

} button_callbacks_t;


typedef struct button_t
{
    /**********************************************************************
     * Driver
     *********************************************************************/

    driver_gpio_t *gpio;


    /**********************************************************************
     * Configuration
     *********************************************************************/

    button_repeat_t repeat_enable;

    uint16_t debounce_time_ms;
    uint16_t short_press_time_ms;
    uint16_t long_press_time_ms;
    uint16_t repeat_start_delay_ms;
    uint16_t repeat_interval_ms;

    driver_gpio_state_t active_state;


    /**********************************************************************
     * Runtime
     *********************************************************************/

    driver_gpio_state_t prev_state;
    driver_gpio_state_t debounce_state;
    uint32_t debounce_start_time;
    bool debounce_active;

    bool short_fired;
    bool long_fired;
    bool repeat_active;

    uint32_t press_start_time;
    uint32_t press_duration;

    uint32_t last_repeat_time;
    uint32_t last_change_time;

    button_status_t status;


    /**********************************************************************
     * User
     *********************************************************************/

    void *user_data;
    const button_callbacks_t *callbacks;

} button_t;





/**
 * @brief Initializes button object.
 *
 * @param obj Pointer to button object.
 * @param gpio Pointer to GPIO driver object.
 * @param active_state GPIO state treated as button pressed.
 * @param repeat_enable Enables or disables auto-repeat.
 * @param debounce_time_ms Debounce time in milliseconds.
 * @param short_press_time_ms Short press threshold in milliseconds.
 * @param long_press_time_ms Long press threshold in milliseconds.
 * @param repeat_start_delay_ms Delay before first repeat event.
 * @param repeat_interval_ms Interval between repeat events.
 * @param callbacks Pointer to callback table. May be NULL.
 * @param user_data User-defined pointer.
 *
 * @return BUTTON_OK on success, otherwise error code.
 */
button_status_t Button_Init(
        button_t *obj,
        driver_gpio_t *gpio,
        driver_gpio_state_t active_state,
        bool repeat_enable,
        uint16_t debounce_time_ms,
        uint16_t short_press_time_ms,
        uint16_t long_press_time_ms,
        uint16_t repeat_start_delay_ms,
        uint16_t repeat_interval_ms,
        const button_callbacks_t *callbacks,
        void *user_data);



/**
 * @brief Updates button state and processes button events.
 *
 * Reads the current GPIO state, performs debounce filtering,
 * detects button press and release events, handles short press,
 * long press and auto-repeat, and invokes registered callbacks.
 *
 * This function should be called periodically from the main loop.
 *
 * @param obj Pointer to button object.
 * @param time_ms Current system time in milliseconds.
 *
 * @return Current button status.
 */
button_status_t Button_Update(
        button_t *obj,
        uint32_t time_ms);



/**
 * @brief Resets button runtime state.
 *
 * Clears all runtime variables and returns the button to the idle state.
 * Configuration parameters, callbacks and user data remain unchanged.
 *
 * @param obj Pointer to button object.
 */
void Button_Reset(button_t *obj);



/**
 * @brief Returns current button status.
 *
 * Returns the last button event generated by Button_Update().
 *
 * @param obj Pointer to button object.
 *
 * @return Current button status.
 */
button_status_t Button_GetStatus(const button_t *obj);




/**
 * @brief Sets button debounce time.
 *
 * @param obj Pointer to button object.
 * @param debounce_time Debounce time in milliseconds.
 */
void Button_SetDebounceTime(
        button_t *obj,
        uint32_t debounce_time);


/**
 * @brief Sets short press detection time.
 *
 * @param obj Pointer to button object.
 * @param short_press_time Short press threshold in milliseconds.
 */
void Button_SetShortPressTime(
        button_t *obj,
        uint32_t short_press_time);


/**
 * @brief Sets long press detection time.
 *
 * @param obj Pointer to button object.
 * @param long_press_time Long press threshold in milliseconds.
 */
void Button_SetLongPressTime(
        button_t *obj,
        uint32_t long_press_time);


/**
 * @brief Enables or disables auto-repeat.
 *
 * @param obj Pointer to button object.
 * @param enable Auto-repeat enable state.
 */
void Button_SetRepeatEnable(
        button_t *obj,
        button_repeat_t enable);


/**
 * @brief Sets auto-repeat start delay.
 *
 * @param obj Pointer to button object.
 * @param repeat_delay_time Delay before the first repeat event in milliseconds.
 */
void Button_SetRepeatStartDelay(
        button_t *obj,
        uint32_t repeat_delay_time);


/**
 * @brief Sets auto-repeat interval.
 *
 * @param obj Pointer to button object.
 * @param repeat_interval_time Time between repeat events in milliseconds.
 */
void Button_SetRepeatInterval(
        button_t *obj,
        uint32_t repeat_interval_time);


/**
 * @brief Registers button callbacks.
 *
 * @param obj Pointer to button object.
 * @param callbacks Pointer to callback table. Set to NULL to disable callbacks.
 */
void Button_SetCallbacks(
        button_t *obj,
        const button_callbacks_t *callbacks);


/**
 * @brief Clears all registered callbacks.
 *
 * @param obj Pointer to button object.
 */
void Button_ClearCallbacks(
        button_t *obj);



WEAK void Button_ShortPressedCallback(button_t *obj);
WEAK void Button_LongPressedCallback(button_t *obj);
WEAK void Button_ShortReleasedCallback(button_t *obj);
WEAK void Button_LongReleasedCallback(button_t *obj);
WEAK void Button_repeatedCallback(button_t *obj);


#ifdef __cplusplus
}
#endif

#endif /* BUTTON_H_ */
